chore: output pr url

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,5 +1,12 @@
 version: 2.1
 commands:
+  install_jq:
+    steps:
+      - run:
+          name: install jq command
+          command: |
+            sudo apt-get update
+            sudo apt-get install -y jq
   set_up_git:
     steps:
       - checkout
@@ -27,13 +34,21 @@ commands:
           name: Create pull request
           # ref: https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#create-a-pull-request
           command: |
-            curl -L \
+            response=$(curl -s -L \
             -X POST \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${GITHUB_TOKEN}" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/ksrnnb/ci_create_pr/pulls \
-            -d '{"title": "create PR test", "body": "PR body dayo", "head": "${BRANCH_NAME}", "base": "main"}'
+            -d '{"title": "create PR test", "body": "PR body dayo", "head": "${BRANCH_NAME}", "base": "main"}')
+
+            pr_url=$(echo $response | jq -r '.html_url')
+            if [ -z "$pr_url" ]; then
+              echo "Error: PR URL not found in the response."
+              exit 1
+            fi
+
+            echo $pr_url
 jobs:
   create_pr_job:
     docker:
@@ -42,6 +57,7 @@ jobs:
       - add_ssh_keys:
           fingerprints:
             - "SHA256:7p8XHnZsyzH7w0g/mBhp4dEeHNO6gPyTV5io5esfZPs"
+      - install_jq
       - set_up_git
       - create_pr
 
